"""
This module defines the database models for the application.
"""
from datetime import datetime, timezone
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()

BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']


class User(UserMixin, db.Model):
    """
    User model for the application.
    """
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    role = db.Column(db.String(20), nullable=False, default='staff')  # admin / staff
    is_active_user = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def set_password(self, password):
        """
        Sets the password for the user.
        """
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        """
        Checks the password for the user.
        """
        return check_password_hash(self.password_hash, password)

    @property
    def is_admin(self):
        """
        Checks if the user is an admin.
        """
        return self.role == 'admin'

    @property
    def is_active(self):
        """
        Checks if the user is active.
        """
        return self.is_active_user

    def __repr__(self):
        return f'<User {self.username}>'


class Donor(db.Model):
    """
    Donor model for the application.
    """
    __tablename__ = 'donors'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    blood_group = db.Column(db.String(5), nullable=False)
    contact = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(120))
    address = db.Column(db.Text)
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    id_proof_path = db.Column(db.String(256))
    last_donation_date = db.Column(db.Date)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return f'<Donor {self.name} ({self.blood_group})>'


class BloodInventory(db.Model):
    """
    BloodInventory model for the application.
    """
    __tablename__ = 'blood_inventory'

    id = db.Column(db.Integer, primary_key=True)
    blood_group = db.Column(db.String(5), unique=True, nullable=False)
    units_available = db.Column(db.Integer, default=0)
    managed_by = db.Column(db.Integer, db.ForeignKey('users.id'))
    last_updated = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc),
                             onupdate=lambda: datetime.now(timezone.utc))

    manager = db.relationship('User', backref='managed_inventory')

    @property
    def status(self):
        """
        Returns the status of the blood inventory.
        """
        if self.units_available <= 2:
            return 'critical'
        if self.units_available <= 5:
            return 'low'
        return 'sufficient'

    def __repr__(self):
        return f'<BloodInventory {self.blood_group}: {self.units_available}>'


class BloodRequest(db.Model):
    """
    BloodRequest model for the application.
    """
    __tablename__ = 'blood_requests'

    id = db.Column(db.Integer, primary_key=True)
    patient_name = db.Column(db.String(100), nullable=False)
    blood_group = db.Column(db.String(5), nullable=False)
    units_required = db.Column(db.Integer, nullable=False, default=1)
    urgency = db.Column(db.String(20), default='normal')  # normal / urgent / critical
    status = db.Column(db.String(20), default='pending')  # pending / approved / rejected
    requested_by = db.Column(db.Integer, db.ForeignKey('users.id'))
    approved_by = db.Column(db.Integer, db.ForeignKey('users.id'))
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc),
                           onupdate=lambda: datetime.now(timezone.utc))

    requester = db.relationship('User', foreign_keys=[requested_by], backref='requests_made')
    approver = db.relationship('User', foreign_keys=[approved_by], backref='requests_approved')

    def __repr__(self):
        return f'<BloodRequest {self.patient_name} ({self.blood_group}) - {self.status}>'


class AnalyticsAlert(db.Model):
    """
    Model to store historical shortage alerts generated by the prediction engine.
    """
    __tablename__ = 'analytics_alerts'

    id = db.Column(db.Integer, primary_key=True)
    blood_group = db.Column(db.String(5), nullable=False)
    current_stock = db.Column(db.Integer, nullable=False)
    predicted_demand = db.Column(db.Float, nullable=False)
    risk_level = db.Column(db.String(20), nullable=False)
    days_until_shortage = db.Column(db.Float)
    timestamp = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return f'<AnalyticsAlert {self.blood_group}: {self.risk_level} @ {self.timestamp}>'


class AuditLog(db.Model):
    """
    AuditLog model for the application.
    """
    __tablename__ = 'audit_logs'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    action = db.Column(db.String(100), nullable=False)
    details = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    user = db.relationship('User', backref='audit_logs')

    def __repr__(self):
        return f'<AuditLog {self.action} by User {self.user_id}>'
